// Code generated by protoc-gen-go. DO NOT EDIT.
// source: web.proto

/*
Package web is a generated protocol buffer package.

It is generated from these files:
	web.proto

It has these top-level messages:
	PkgDest
	Request
	Response
	Item
	PkgDetail
	Package
	Status
*/
package web

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PkgDest struct {
	PackageId        *int64 `protobuf:"varint,1,req,name=package_id" json:"package_id,omitempty"`
	X                *int32 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	UserId           *int64 `protobuf:"varint,4,req,name=user_id" json:"user_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *PkgDest) Reset()                    { *m = PkgDest{} }
func (m *PkgDest) String() string            { return proto.CompactTextString(m) }
func (*PkgDest) ProtoMessage()               {}
func (*PkgDest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PkgDest) GetPackageId() int64 {
	if m != nil && m.PackageId != nil {
		return *m.PackageId
	}
	return 0
}

func (m *PkgDest) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *PkgDest) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *PkgDest) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

type Request struct {
	NewUser           *string  `protobuf:"bytes,1,opt,name=new_user" json:"new_user,omitempty"`
	GetPackages       *int64   `protobuf:"varint,2,opt,name=get_packages" json:"get_packages,omitempty"`
	GetPackageStatus  []int64  `protobuf:"varint,3,rep,name=get_package_status" json:"get_package_status,omitempty"`
	ChangeDestination *PkgDest `protobuf:"bytes,4,opt,name=change_destination" json:"change_destination,omitempty"`
	XXX_unrecognized  []byte   `json:"-"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Request) GetNewUser() string {
	if m != nil && m.NewUser != nil {
		return *m.NewUser
	}
	return ""
}

func (m *Request) GetGetPackages() int64 {
	if m != nil && m.GetPackages != nil {
		return *m.GetPackages
	}
	return 0
}

func (m *Request) GetGetPackageStatus() []int64 {
	if m != nil {
		return m.GetPackageStatus
	}
	return nil
}

func (m *Request) GetChangeDestination() *PkgDest {
	if m != nil {
		return m.ChangeDestination
	}
	return nil
}

type Response struct {
	UserId           *int64     `protobuf:"varint,1,opt,name=user_id" json:"user_id,omitempty"`
	Packages         []*Package `protobuf:"bytes,2,rep,name=packages" json:"packages,omitempty"`
	Error            *string    `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Response) GetUserId() int64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Response) GetPackages() []*Package {
	if m != nil {
		return m.Packages
	}
	return nil
}

func (m *Response) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type Item struct {
	Description      *string `protobuf:"bytes,1,req,name=description" json:"description,omitempty"`
	Amount           *int32  `protobuf:"varint,2,req,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Item) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Item) GetAmount() int32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

type PkgDetail struct {
	Items            []*Item `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	X                *int32  `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y                *int32  `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PkgDetail) Reset()                    { *m = PkgDetail{} }
func (m *PkgDetail) String() string            { return proto.CompactTextString(m) }
func (*PkgDetail) ProtoMessage()               {}
func (*PkgDetail) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PkgDetail) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *PkgDetail) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *PkgDetail) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type Package struct {
	PackageId        *int64     `protobuf:"varint,1,req,name=package_id" json:"package_id,omitempty"`
	Detail           *PkgDetail `protobuf:"bytes,2,req,name=detail" json:"detail,omitempty"`
	Status           []*Status  `protobuf:"bytes,3,rep,name=status" json:"status,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Package) Reset()                    { *m = Package{} }
func (m *Package) String() string            { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()               {}
func (*Package) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Package) GetPackageId() int64 {
	if m != nil && m.PackageId != nil {
		return *m.PackageId
	}
	return 0
}

func (m *Package) GetDetail() *PkgDetail {
	if m != nil {
		return m.Detail
	}
	return nil
}

func (m *Package) GetStatus() []*Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type Status struct {
	Status           *string `protobuf:"bytes,1,req,name=status" json:"status,omitempty"`
	Timestamp        *int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Status) GetStatus() string {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return ""
}

func (m *Status) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*PkgDest)(nil), "web.PkgDest")
	proto.RegisterType((*Request)(nil), "web.Request")
	proto.RegisterType((*Response)(nil), "web.Response")
	proto.RegisterType((*Item)(nil), "web.Item")
	proto.RegisterType((*PkgDetail)(nil), "web.PkgDetail")
	proto.RegisterType((*Package)(nil), "web.Package")
	proto.RegisterType((*Status)(nil), "web.Status")
}

func init() { proto.RegisterFile("web.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x4f, 0x6b, 0xe3, 0x30,
	0x10, 0xc5, 0x91, 0x95, 0xd8, 0xd1, 0x38, 0x9b, 0xdd, 0xd5, 0xee, 0x41, 0xb4, 0x10, 0x8c, 0x4e,
	0x82, 0x40, 0x0e, 0xb9, 0xf6, 0x9a, 0x4b, 0x7b, 0x2a, 0xe9, 0xad, 0x17, 0xa3, 0xc4, 0x83, 0x2b,
	0x52, 0xff, 0xa9, 0x25, 0xe3, 0xf6, 0xdb, 0x17, 0xc9, 0x29, 0xf1, 0x21, 0xb7, 0x61, 0x34, 0xf3,
	0xde, 0x6f, 0x9e, 0x80, 0x0d, 0x78, 0xdc, 0xb6, 0x5d, 0xe3, 0x1a, 0x4e, 0x07, 0x3c, 0xca, 0x3d,
	0x24, 0xcf, 0xe7, 0x72, 0x8f, 0xd6, 0x71, 0x0e, 0xd0, 0xea, 0xd3, 0x59, 0x97, 0x98, 0x9b, 0x42,
	0x90, 0x2c, 0x52, 0x94, 0x33, 0x20, 0x9f, 0x22, 0xca, 0x22, 0x35, 0xf7, 0xe5, 0x97, 0xa0, 0xa1,
	0xfc, 0x0d, 0x49, 0x6f, 0xb1, 0xf3, 0x63, 0x33, 0x3f, 0x26, 0x07, 0x48, 0x0e, 0xf8, 0xd1, 0x7b,
	0x95, 0x3f, 0xb0, 0xa8, 0x71, 0xc8, 0xfd, 0xbb, 0x20, 0x19, 0x51, 0x8c, 0xff, 0x87, 0x65, 0x89,
	0x2e, 0xbf, 0x68, 0x5b, 0x11, 0x65, 0x44, 0x51, 0x7e, 0x07, 0x7c, 0xd2, 0xcd, 0xad, 0xd3, 0xae,
	0xb7, 0x82, 0x66, 0x54, 0x51, 0xae, 0x80, 0x9f, 0xde, 0x74, 0x5d, 0x62, 0x5e, 0xa0, 0x75, 0xa6,
	0xd6, 0xce, 0x34, 0xb5, 0x98, 0x65, 0x44, 0xa5, 0xbb, 0xe5, 0xd6, 0x5f, 0x70, 0x61, 0x96, 0x4f,
	0xb0, 0x38, 0xa0, 0x6d, 0x9b, 0xda, 0xe2, 0x94, 0x8a, 0x04, 0x8b, 0x35, 0x2c, 0x26, 0xa6, 0xf4,
	0xba, 0x3c, 0x36, 0xf9, 0x2f, 0x98, 0x63, 0xd7, 0x35, 0x9d, 0xa0, 0x9e, 0x53, 0x6e, 0x60, 0xf6,
	0xe8, 0xb0, 0xe2, 0xff, 0x20, 0x2d, 0xd0, 0x9e, 0x3a, 0xd3, 0x06, 0x5b, 0x1f, 0x04, 0xe3, 0x2b,
	0x88, 0x75, 0xd5, 0xf4, 0xb5, 0x1b, 0xd3, 0x90, 0x0f, 0xc0, 0x02, 0x83, 0xd3, 0xe6, 0x9d, 0x0b,
	0x98, 0x1b, 0x87, 0x95, 0x15, 0x24, 0xb8, 0xb0, 0xe0, 0x12, 0xb4, 0x6e, 0xe6, 0x27, 0x5f, 0x21,
	0xf9, 0x61, 0xb8, 0x15, 0xfa, 0x1a, 0xe2, 0x22, 0x08, 0x87, 0xcd, 0x74, 0xb7, 0xba, 0x9e, 0x1c,
	0xec, 0xee, 0x21, 0x9e, 0xc4, 0x95, 0xee, 0xd2, 0xf0, 0xfe, 0x12, 0x5a, 0x72, 0x03, 0xf1, 0x58,
	0x79, 0xe4, 0xcb, 0xd8, 0x78, 0xc2, 0x5f, 0x60, 0xce, 0x54, 0x68, 0x9d, 0xae, 0xda, 0xf1, 0x13,
	0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4b, 0x2c, 0x5a, 0x1a, 0x0e, 0x02, 0x00, 0x00,
}
