# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ups_comm.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ups_comm.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0eups_comm.proto\"5\n\tFTransfer\x12\x12\n\npackage_id\x18\x01 \x02(\x03\x12\t\n\x01x\x18\x02 \x02(\x05\x12\t\n\x01y\x18\x03 \x02(\x05\"`\n\tFCommands\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\x03\x12\x12\n\npackage_id\x18\x03 \x01(\x03\x12\x1c\n\x08transfer\x18\x04 \x01(\x0b\x32\n.FTransfer\"I\n\tFResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x1c\n\tpack_info\x18\x02 \x03(\x0b\x32\t.BPackage\x12\r\n\x05\x65rror\x18\x03 \x01(\t\"R\n\x08\x42Package\x12\x15\n\x06\x64\x65tail\x18\x01 \x03(\x0b\x32\x05.Item\x12\x12\n\npackage_id\x18\x02 \x02(\x03\x12\x1b\n\x06status\x18\x03 \x03(\x0b\x32\x0b.PackStatus\"+\n\x04Item\x12\x13\n\x0b\x64\x65scription\x18\x01 \x02(\t\x12\x0e\n\x06\x61mount\x18\x02 \x02(\x05\"\x1e\n\nPackStatus\x12\x10\n\x08progress\x18\x01 \x02(\t')
)




_FTRANSFER = _descriptor.Descriptor(
  name='FTransfer',
  full_name='FTransfer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package_id', full_name='FTransfer.package_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='FTransfer.x', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='FTransfer.y', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=71,
)


_FCOMMANDS = _descriptor.Descriptor(
  name='FCommands',
  full_name='FCommands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='FCommands.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='FCommands.user_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package_id', full_name='FCommands.package_id', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='transfer', full_name='FCommands.transfer', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=169,
)


_FRESPONSE = _descriptor.Descriptor(
  name='FResponse',
  full_name='FResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='FResponse.user_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pack_info', full_name='FResponse.pack_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='FResponse.error', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=244,
)


_BPACKAGE = _descriptor.Descriptor(
  name='BPackage',
  full_name='BPackage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detail', full_name='BPackage.detail', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='package_id', full_name='BPackage.package_id', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='BPackage.status', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=328,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='description', full_name='Item.description', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='Item.amount', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=330,
  serialized_end=373,
)


_PACKSTATUS = _descriptor.Descriptor(
  name='PackStatus',
  full_name='PackStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='progress', full_name='PackStatus.progress', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=405,
)

_FCOMMANDS.fields_by_name['transfer'].message_type = _FTRANSFER
_FRESPONSE.fields_by_name['pack_info'].message_type = _BPACKAGE
_BPACKAGE.fields_by_name['detail'].message_type = _ITEM
_BPACKAGE.fields_by_name['status'].message_type = _PACKSTATUS
DESCRIPTOR.message_types_by_name['FTransfer'] = _FTRANSFER
DESCRIPTOR.message_types_by_name['FCommands'] = _FCOMMANDS
DESCRIPTOR.message_types_by_name['FResponse'] = _FRESPONSE
DESCRIPTOR.message_types_by_name['BPackage'] = _BPACKAGE
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['PackStatus'] = _PACKSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FTransfer = _reflection.GeneratedProtocolMessageType('FTransfer', (_message.Message,), dict(
  DESCRIPTOR = _FTRANSFER,
  __module__ = 'ups_comm_pb2'
  # @@protoc_insertion_point(class_scope:FTransfer)
  ))
_sym_db.RegisterMessage(FTransfer)

FCommands = _reflection.GeneratedProtocolMessageType('FCommands', (_message.Message,), dict(
  DESCRIPTOR = _FCOMMANDS,
  __module__ = 'ups_comm_pb2'
  # @@protoc_insertion_point(class_scope:FCommands)
  ))
_sym_db.RegisterMessage(FCommands)

FResponse = _reflection.GeneratedProtocolMessageType('FResponse', (_message.Message,), dict(
  DESCRIPTOR = _FRESPONSE,
  __module__ = 'ups_comm_pb2'
  # @@protoc_insertion_point(class_scope:FResponse)
  ))
_sym_db.RegisterMessage(FResponse)

BPackage = _reflection.GeneratedProtocolMessageType('BPackage', (_message.Message,), dict(
  DESCRIPTOR = _BPACKAGE,
  __module__ = 'ups_comm_pb2'
  # @@protoc_insertion_point(class_scope:BPackage)
  ))
_sym_db.RegisterMessage(BPackage)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'ups_comm_pb2'
  # @@protoc_insertion_point(class_scope:Item)
  ))
_sym_db.RegisterMessage(Item)

PackStatus = _reflection.GeneratedProtocolMessageType('PackStatus', (_message.Message,), dict(
  DESCRIPTOR = _PACKSTATUS,
  __module__ = 'ups_comm_pb2'
  # @@protoc_insertion_point(class_scope:PackStatus)
  ))
_sym_db.RegisterMessage(PackStatus)


# @@protoc_insertion_point(module_scope)
