// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ups.proto

/*
Package ups is a generated protocol buffer package.

It is generated from these files:
	ups.proto

It has these top-level messages:
	Connect
	Connected
	GoPickup
	Finished
	DeliveryMade
	DeliveryLocation
	GoDeliver
	Commands
	Responses
*/
package ups

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Connect struct {
	ReconnectId      *int64 `protobuf:"varint,1,opt,name=reconnect_id" json:"reconnect_id,omitempty"`
	NumTrucksInit    *int32 `protobuf:"varint,2,opt,name=num_trucks_init" json:"num_trucks_init,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Connect) Reset()                    { *m = Connect{} }
func (m *Connect) String() string            { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()               {}
func (*Connect) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Connect) GetReconnectId() int64 {
	if m != nil && m.ReconnectId != nil {
		return *m.ReconnectId
	}
	return 0
}

func (m *Connect) GetNumTrucksInit() int32 {
	if m != nil && m.NumTrucksInit != nil {
		return *m.NumTrucksInit
	}
	return 0
}

type Connected struct {
	WorldId          *int64  `protobuf:"varint,1,req,name=world_id" json:"world_id,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Connected) Reset()                    { *m = Connected{} }
func (m *Connected) String() string            { return proto.CompactTextString(m) }
func (*Connected) ProtoMessage()               {}
func (*Connected) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Connected) GetWorldId() int64 {
	if m != nil && m.WorldId != nil {
		return *m.WorldId
	}
	return 0
}

func (m *Connected) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type GoPickup struct {
	TruckId          *int32 `protobuf:"varint,1,req,name=truck_id" json:"truck_id,omitempty"`
	WarehouseId      *int32 `protobuf:"varint,2,req,name=warehouse_id" json:"warehouse_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *GoPickup) Reset()                    { *m = GoPickup{} }
func (m *GoPickup) String() string            { return proto.CompactTextString(m) }
func (*GoPickup) ProtoMessage()               {}
func (*GoPickup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GoPickup) GetTruckId() int32 {
	if m != nil && m.TruckId != nil {
		return *m.TruckId
	}
	return 0
}

func (m *GoPickup) GetWarehouseId() int32 {
	if m != nil && m.WarehouseId != nil {
		return *m.WarehouseId
	}
	return 0
}

type Finished struct {
	TruckId          *int32 `protobuf:"varint,1,req,name=truck_id" json:"truck_id,omitempty"`
	X                *int32 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Finished) Reset()                    { *m = Finished{} }
func (m *Finished) String() string            { return proto.CompactTextString(m) }
func (*Finished) ProtoMessage()               {}
func (*Finished) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Finished) GetTruckId() int32 {
	if m != nil && m.TruckId != nil {
		return *m.TruckId
	}
	return 0
}

func (m *Finished) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Finished) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type DeliveryMade struct {
	TruckId          *int32 `protobuf:"varint,1,req,name=truck_id" json:"truck_id,omitempty"`
	PackageId        *int64 `protobuf:"varint,2,req,name=package_id" json:"package_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeliveryMade) Reset()                    { *m = DeliveryMade{} }
func (m *DeliveryMade) String() string            { return proto.CompactTextString(m) }
func (*DeliveryMade) ProtoMessage()               {}
func (*DeliveryMade) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *DeliveryMade) GetTruckId() int32 {
	if m != nil && m.TruckId != nil {
		return *m.TruckId
	}
	return 0
}

func (m *DeliveryMade) GetPackageId() int64 {
	if m != nil && m.PackageId != nil {
		return *m.PackageId
	}
	return 0
}

type DeliveryLocation struct {
	PackageId        *int64 `protobuf:"varint,1,req,name=package_id" json:"package_id,omitempty"`
	X                *int32 `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y                *int32 `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *DeliveryLocation) Reset()                    { *m = DeliveryLocation{} }
func (m *DeliveryLocation) String() string            { return proto.CompactTextString(m) }
func (*DeliveryLocation) ProtoMessage()               {}
func (*DeliveryLocation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeliveryLocation) GetPackageId() int64 {
	if m != nil && m.PackageId != nil {
		return *m.PackageId
	}
	return 0
}

func (m *DeliveryLocation) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *DeliveryLocation) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

type GoDeliver struct {
	Truckid          *int32              `protobuf:"varint,1,req,name=truckid" json:"truckid,omitempty"`
	Packages         []*DeliveryLocation `protobuf:"bytes,2,rep,name=packages" json:"packages,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GoDeliver) Reset()                    { *m = GoDeliver{} }
func (m *GoDeliver) String() string            { return proto.CompactTextString(m) }
func (*GoDeliver) ProtoMessage()               {}
func (*GoDeliver) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GoDeliver) GetTruckid() int32 {
	if m != nil && m.Truckid != nil {
		return *m.Truckid
	}
	return 0
}

func (m *GoDeliver) GetPackages() []*DeliveryLocation {
	if m != nil {
		return m.Packages
	}
	return nil
}

type Commands struct {
	Deliveries       []*GoDeliver `protobuf:"bytes,1,rep,name=deliveries" json:"deliveries,omitempty"`
	Pickups          []*GoPickup  `protobuf:"bytes,2,rep,name=pickups" json:"pickups,omitempty"`
	SimSpeed         *uint32      `protobuf:"varint,3,opt,name=sim_speed" json:"sim_speed,omitempty"`
	Disconnect       *bool        `protobuf:"varint,4,opt,name=disconnect" json:"disconnect,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Commands) Reset()                    { *m = Commands{} }
func (m *Commands) String() string            { return proto.CompactTextString(m) }
func (*Commands) ProtoMessage()               {}
func (*Commands) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Commands) GetDeliveries() []*GoDeliver {
	if m != nil {
		return m.Deliveries
	}
	return nil
}

func (m *Commands) GetPickups() []*GoPickup {
	if m != nil {
		return m.Pickups
	}
	return nil
}

func (m *Commands) GetSimSpeed() uint32 {
	if m != nil && m.SimSpeed != nil {
		return *m.SimSpeed
	}
	return 0
}

func (m *Commands) GetDisconnect() bool {
	if m != nil && m.Disconnect != nil {
		return *m.Disconnect
	}
	return false
}

type Responses struct {
	Completions      []*Finished     `protobuf:"bytes,1,rep,name=completions" json:"completions,omitempty"`
	Delivered        []*DeliveryMade `protobuf:"bytes,2,rep,name=delivered" json:"delivered,omitempty"`
	Error            *string         `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
	Finished         *bool           `protobuf:"varint,4,opt,name=finished" json:"finished,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *Responses) Reset()                    { *m = Responses{} }
func (m *Responses) String() string            { return proto.CompactTextString(m) }
func (*Responses) ProtoMessage()               {}
func (*Responses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Responses) GetCompletions() []*Finished {
	if m != nil {
		return m.Completions
	}
	return nil
}

func (m *Responses) GetDelivered() []*DeliveryMade {
	if m != nil {
		return m.Delivered
	}
	return nil
}

func (m *Responses) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *Responses) GetFinished() bool {
	if m != nil && m.Finished != nil {
		return *m.Finished
	}
	return false
}

func init() {
	proto.RegisterType((*Connect)(nil), "Connect")
	proto.RegisterType((*Connected)(nil), "Connected")
	proto.RegisterType((*GoPickup)(nil), "GoPickup")
	proto.RegisterType((*Finished)(nil), "Finished")
	proto.RegisterType((*DeliveryMade)(nil), "DeliveryMade")
	proto.RegisterType((*DeliveryLocation)(nil), "DeliveryLocation")
	proto.RegisterType((*GoDeliver)(nil), "GoDeliver")
	proto.RegisterType((*Commands)(nil), "Commands")
	proto.RegisterType((*Responses)(nil), "Responses")
}

func init() { proto.RegisterFile("ups.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 356 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x18, 0x86, 0x69, 0xeb, 0x58, 0xf3, 0x6d, 0x63, 0x5b, 0x11, 0x2c, 0x1e, 0xa4, 0xd4, 0x4b, 0x0f,
	0xd2, 0xc3, 0xf0, 0xe0, 0xc1, 0x8b, 0x4c, 0xdc, 0x45, 0x41, 0xfc, 0x03, 0xa5, 0x34, 0x9f, 0x2e,
	0x6c, 0x4d, 0x42, 0xd2, 0x3a, 0xf7, 0xef, 0x25, 0x4d, 0x5a, 0x71, 0xec, 0xd6, 0x26, 0xef, 0xf3,
	0x3d, 0xc9, 0x1b, 0x20, 0xad, 0xd4, 0xb9, 0x54, 0xa2, 0x11, 0xe9, 0x03, 0x8c, 0xd7, 0x82, 0x73,
	0xac, 0x9a, 0xe8, 0x12, 0xa6, 0x0a, 0x2b, 0xfb, 0x53, 0x30, 0x1a, 0x7b, 0x89, 0x97, 0x05, 0xd1,
	0x15, 0xcc, 0x79, 0x5b, 0x17, 0x8d, 0x6a, 0xab, 0x9d, 0x2e, 0x18, 0x67, 0x4d, 0xec, 0x27, 0x5e,
	0x36, 0x4a, 0xef, 0x80, 0x38, 0x12, 0x69, 0xb4, 0x80, 0xf0, 0x20, 0xd4, 0x9e, 0x5a, 0xce, 0xcf,
	0x82, 0x68, 0x06, 0x23, 0x54, 0x4a, 0xa8, 0x2e, 0x4d, 0xd2, 0x15, 0x84, 0x1b, 0xf1, 0xce, 0xaa,
	0x5d, 0x2b, 0x4d, 0xb8, 0x1b, 0xd7, 0x87, 0x47, 0x46, 0x7d, 0x28, 0x15, 0x6e, 0x45, 0xab, 0xd1,
	0xac, 0xfa, 0x66, 0xd5, 0x30, 0x2f, 0x8c, 0x33, 0xbd, 0xb5, 0x82, 0x13, 0x86, 0x80, 0xf7, 0x63,
	0x83, 0xe6, 0xf3, 0x18, 0x07, 0x1d, 0x73, 0x0f, 0xd3, 0x67, 0xdc, 0xb3, 0x6f, 0x54, 0xc7, 0xb7,
	0x92, 0xe2, 0x19, 0x2e, 0x02, 0x90, 0x65, 0xb5, 0x2b, 0xbf, 0x06, 0x53, 0x90, 0x3e, 0xc2, 0xa2,
	0xa7, 0x5e, 0x45, 0x55, 0x36, 0x4c, 0xf0, 0x93, 0x9c, 0xbd, 0xd4, 0x79, 0xe7, 0x13, 0x90, 0x8d,
	0x70, 0x7c, 0x34, 0x87, 0x71, 0x27, 0x1c, 0x7c, 0xb7, 0x10, 0xba, 0x39, 0x3a, 0xf6, 0x93, 0x20,
	0x9b, 0xac, 0x96, 0xf9, 0xa9, 0x2c, 0xad, 0x21, 0x5c, 0x8b, 0xba, 0x2e, 0x39, 0xd5, 0xd1, 0x0d,
	0x00, 0xb5, 0xfb, 0x0c, 0x75, 0xec, 0x75, 0x08, 0xe4, 0x7f, 0x86, 0x6b, 0x18, 0xcb, 0xae, 0xc8,
	0x7e, 0x1e, 0xc9, 0x87, 0x6a, 0x97, 0x40, 0x34, 0xab, 0x0b, 0x2d, 0x11, 0x69, 0x1c, 0x24, 0x5e,
	0x36, 0x33, 0xf7, 0xa0, 0x4c, 0xbb, 0x77, 0x8d, 0x2f, 0x12, 0x2f, 0x0b, 0x53, 0x0e, 0xe4, 0x03,
	0xb5, 0x14, 0x5c, 0xa3, 0xf1, 0x4d, 0x2a, 0x51, 0xcb, 0x3d, 0x9a, 0x93, 0xf4, 0x42, 0x92, 0x0f,
	0xd5, 0x27, 0x40, 0xdc, 0x79, 0x90, 0x3a, 0xe3, 0x2c, 0xff, 0x57, 0xf2, 0xf0, 0xd6, 0xc6, 0x48,
	0x4c, 0xe7, 0x9f, 0x0e, 0xb6, 0xbe, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4f, 0x27, 0x49, 0x4d,
	0x71, 0x02, 0x00, 0x00,
}
