// Code generated by protoc-gen-go. DO NOT EDIT.
// source: package_items.proto

/*
Package db is a generated protocol buffer package.

It is generated from these files:
	package_items.proto

It has these top-level messages:
	PackageItems
	PackageItem
*/
package db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PackageItems struct {
	Items            []*PackageItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *PackageItems) Reset()                    { *m = PackageItems{} }
func (m *PackageItems) String() string            { return proto.CompactTextString(m) }
func (*PackageItems) ProtoMessage()               {}
func (*PackageItems) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PackageItems) GetItems() []*PackageItem {
	if m != nil {
		return m.Items
	}
	return nil
}

type PackageItem struct {
	Description      *string `protobuf:"bytes,1,req,name=description" json:"description,omitempty"`
	Count            *int32  `protobuf:"varint,2,req,name=count" json:"count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PackageItem) Reset()                    { *m = PackageItem{} }
func (m *PackageItem) String() string            { return proto.CompactTextString(m) }
func (*PackageItem) ProtoMessage()               {}
func (*PackageItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PackageItem) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *PackageItem) GetCount() int32 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*PackageItems)(nil), "db.PackageItems")
	proto.RegisterType((*PackageItem)(nil), "db.PackageItem")
}

func init() { proto.RegisterFile("package_items.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x48, 0x4c, 0xce,
	0x4e, 0x4c, 0x4f, 0x8d, 0xcf, 0x2c, 0x49, 0xcd, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x4a, 0x49, 0x52, 0xd2, 0xe3, 0xe2, 0x09, 0x80, 0x48, 0x79, 0x82, 0x64, 0x84, 0xe4, 0xb8,
	0x58, 0xc1, 0x4a, 0x24, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0xf8, 0xf5, 0x52, 0x92, 0xf4, 0x90,
	0x14, 0x28, 0x19, 0x72, 0x71, 0x23, 0x71, 0x85, 0x84, 0xb9, 0xb8, 0x53, 0x52, 0x8b, 0x93, 0x8b,
	0x32, 0x0b, 0x4a, 0x32, 0xf3, 0xf3, 0x24, 0x18, 0x15, 0x98, 0x34, 0x38, 0x85, 0x78, 0xb9, 0x58,
	0x93, 0xf3, 0x4b, 0xf3, 0x4a, 0x24, 0x98, 0x14, 0x98, 0x34, 0x58, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xd8, 0x0c, 0x3d, 0x7b, 0x7c, 0x00, 0x00, 0x00,
}
