# Generated by Django 2.0.4 on 2018-04-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_ups', '0004_remove_user_id_recv_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_id_recv',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
