# Generated by Django 2.0.4 on 2018-04-26 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_ups', '0006_auto_20180426_0501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upsid',
            old_name='ups_id',
            new_name='value',
        ),
    ]
