# Generated by Django 2.0.4 on 2018-04-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_ups', '0002_auto_20180419_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_id_recv',
            name='user',
        ),
        migrations.AddField(
            model_name='user_id_recv',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
