# Generated by Django 2.0.4 on 2018-04-20 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_ups', '0003_auto_20180419_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_id_recv',
            name='username',
        ),
    ]
