// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bridge.proto

/*
Package bridge is a generated protocol buffer package.

It is generated from these files:
	bridge.proto

It has these top-level messages:
	Item
	Package
	RequestTruck
	PackagesLoaded
	ACommands
	ResponsePackageId
	Acknowledgement
	UResponses
	TruckArrival
	Delivery
	UCommands
	AResponses
*/
package bridge

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Item struct {
	ItemId           *int64  `protobuf:"varint,1,req,name=item_id" json:"item_id,omitempty"`
	Description      *string `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	Amount           *int32  `protobuf:"varint,3,req,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Item) GetItemId() int64 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *Item) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Item) GetAmount() int32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

type Package struct {
	WarehouseId      *int32  `protobuf:"varint,1,req,name=warehouse_id" json:"warehouse_id,omitempty"`
	UpsUserId        *int64  `protobuf:"varint,2,opt,name=ups_user_id" json:"ups_user_id,omitempty"`
	X                *int32  `protobuf:"varint,3,req,name=x" json:"x,omitempty"`
	Y                *int32  `protobuf:"varint,4,req,name=y" json:"y,omitempty"`
	Items            []*Item `protobuf:"bytes,5,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Package) Reset()                    { *m = Package{} }
func (m *Package) String() string            { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()               {}
func (*Package) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Package) GetWarehouseId() int32 {
	if m != nil && m.WarehouseId != nil {
		return *m.WarehouseId
	}
	return 0
}

func (m *Package) GetUpsUserId() int64 {
	if m != nil && m.UpsUserId != nil {
		return *m.UpsUserId
	}
	return 0
}

func (m *Package) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Package) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Package) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type RequestTruck struct {
	WarehouseId      *int32 `protobuf:"varint,1,req,name=warehouse_id" json:"warehouse_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RequestTruck) Reset()                    { *m = RequestTruck{} }
func (m *RequestTruck) String() string            { return proto.CompactTextString(m) }
func (*RequestTruck) ProtoMessage()               {}
func (*RequestTruck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestTruck) GetWarehouseId() int32 {
	if m != nil && m.WarehouseId != nil {
		return *m.WarehouseId
	}
	return 0
}

type PackagesLoaded struct {
	TruckId          *int32  `protobuf:"varint,1,req,name=truck_id" json:"truck_id,omitempty"`
	WarehouseId      *int32  `protobuf:"varint,2,req,name=warehouse_id" json:"warehouse_id,omitempty"`
	PackageIds       []int64 `protobuf:"varint,3,rep,name=package_ids" json:"package_ids,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PackagesLoaded) Reset()                    { *m = PackagesLoaded{} }
func (m *PackagesLoaded) String() string            { return proto.CompactTextString(m) }
func (*PackagesLoaded) ProtoMessage()               {}
func (*PackagesLoaded) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PackagesLoaded) GetTruckId() int32 {
	if m != nil && m.TruckId != nil {
		return *m.TruckId
	}
	return 0
}

func (m *PackagesLoaded) GetWarehouseId() int32 {
	if m != nil && m.WarehouseId != nil {
		return *m.WarehouseId
	}
	return 0
}

func (m *PackagesLoaded) GetPackageIds() []int64 {
	if m != nil {
		return m.PackageIds
	}
	return nil
}

type ACommands struct {
	PackageIdReq     *Package        `protobuf:"bytes,1,opt,name=package_id_req" json:"package_id_req,omitempty"`
	TruckReq         *RequestTruck   `protobuf:"bytes,2,opt,name=truck_req" json:"truck_req,omitempty"`
	Loaded           *PackagesLoaded `protobuf:"bytes,3,opt,name=loaded" json:"loaded,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *ACommands) Reset()                    { *m = ACommands{} }
func (m *ACommands) String() string            { return proto.CompactTextString(m) }
func (*ACommands) ProtoMessage()               {}
func (*ACommands) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ACommands) GetPackageIdReq() *Package {
	if m != nil {
		return m.PackageIdReq
	}
	return nil
}

func (m *ACommands) GetTruckReq() *RequestTruck {
	if m != nil {
		return m.TruckReq
	}
	return nil
}

func (m *ACommands) GetLoaded() *PackagesLoaded {
	if m != nil {
		return m.Loaded
	}
	return nil
}

type ResponsePackageId struct {
	PackageId        *int64  `protobuf:"varint,1,req,name=package_id" json:"package_id,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResponsePackageId) Reset()                    { *m = ResponsePackageId{} }
func (m *ResponsePackageId) String() string            { return proto.CompactTextString(m) }
func (*ResponsePackageId) ProtoMessage()               {}
func (*ResponsePackageId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ResponsePackageId) GetPackageId() int64 {
	if m != nil && m.PackageId != nil {
		return *m.PackageId
	}
	return 0
}

func (m *ResponsePackageId) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type Acknowledgement struct {
	Success          *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Acknowledgement) Reset()                    { *m = Acknowledgement{} }
func (m *Acknowledgement) String() string            { return proto.CompactTextString(m) }
func (*Acknowledgement) ProtoMessage()               {}
func (*Acknowledgement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Acknowledgement) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *Acknowledgement) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type UResponses struct {
	PackageId        *ResponsePackageId `protobuf:"bytes,1,opt,name=package_id" json:"package_id,omitempty"`
	Ack              *Acknowledgement   `protobuf:"bytes,2,opt,name=ack" json:"ack,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *UResponses) Reset()                    { *m = UResponses{} }
func (m *UResponses) String() string            { return proto.CompactTextString(m) }
func (*UResponses) ProtoMessage()               {}
func (*UResponses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UResponses) GetPackageId() *ResponsePackageId {
	if m != nil {
		return m.PackageId
	}
	return nil
}

func (m *UResponses) GetAck() *Acknowledgement {
	if m != nil {
		return m.Ack
	}
	return nil
}

type TruckArrival struct {
	TruckId          *int32 `protobuf:"varint,1,req,name=truck_id" json:"truck_id,omitempty"`
	WarehouseId      *int32 `protobuf:"varint,2,req,name=warehouse_id" json:"warehouse_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TruckArrival) Reset()                    { *m = TruckArrival{} }
func (m *TruckArrival) String() string            { return proto.CompactTextString(m) }
func (*TruckArrival) ProtoMessage()               {}
func (*TruckArrival) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TruckArrival) GetTruckId() int32 {
	if m != nil && m.TruckId != nil {
		return *m.TruckId
	}
	return 0
}

func (m *TruckArrival) GetWarehouseId() int32 {
	if m != nil && m.WarehouseId != nil {
		return *m.WarehouseId
	}
	return 0
}

type Delivery struct {
	PackageId        *int64 `protobuf:"varint,1,req,name=package_id" json:"package_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Delivery) Reset()                    { *m = Delivery{} }
func (m *Delivery) String() string            { return proto.CompactTextString(m) }
func (*Delivery) ProtoMessage()               {}
func (*Delivery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *Delivery) GetPackageId() int64 {
	if m != nil && m.PackageId != nil {
		return *m.PackageId
	}
	return 0
}

type UCommands struct {
	Arrival          *TruckArrival `protobuf:"bytes,1,opt,name=arrival" json:"arrival,omitempty"`
	Delivered        *Delivery     `protobuf:"bytes,2,opt,name=delivered" json:"delivered,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *UCommands) Reset()                    { *m = UCommands{} }
func (m *UCommands) String() string            { return proto.CompactTextString(m) }
func (*UCommands) ProtoMessage()               {}
func (*UCommands) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UCommands) GetArrival() *TruckArrival {
	if m != nil {
		return m.Arrival
	}
	return nil
}

func (m *UCommands) GetDelivered() *Delivery {
	if m != nil {
		return m.Delivered
	}
	return nil
}

type AResponses struct {
	Ack              *Acknowledgement `protobuf:"bytes,1,opt,name=ack" json:"ack,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (m *AResponses) Reset()                    { *m = AResponses{} }
func (m *AResponses) String() string            { return proto.CompactTextString(m) }
func (*AResponses) ProtoMessage()               {}
func (*AResponses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AResponses) GetAck() *Acknowledgement {
	if m != nil {
		return m.Ack
	}
	return nil
}

func init() {
	proto.RegisterType((*Item)(nil), "bridge.Item")
	proto.RegisterType((*Package)(nil), "bridge.Package")
	proto.RegisterType((*RequestTruck)(nil), "bridge.RequestTruck")
	proto.RegisterType((*PackagesLoaded)(nil), "bridge.PackagesLoaded")
	proto.RegisterType((*ACommands)(nil), "bridge.ACommands")
	proto.RegisterType((*ResponsePackageId)(nil), "bridge.ResponsePackageId")
	proto.RegisterType((*Acknowledgement)(nil), "bridge.Acknowledgement")
	proto.RegisterType((*UResponses)(nil), "bridge.UResponses")
	proto.RegisterType((*TruckArrival)(nil), "bridge.TruckArrival")
	proto.RegisterType((*Delivery)(nil), "bridge.Delivery")
	proto.RegisterType((*UCommands)(nil), "bridge.UCommands")
	proto.RegisterType((*AResponses)(nil), "bridge.AResponses")
}

func init() { proto.RegisterFile("bridge.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 444 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x95, 0x78, 0x69, 0x9b, 0xd7, 0xd0, 0x0e, 0x33, 0x41, 0x10, 0x12, 0x8a, 0xcc, 0x60,
	0xb9, 0x30, 0x89, 0x1e, 0x76, 0xe2, 0x52, 0xc1, 0x65, 0x12, 0x48, 0x68, 0x62, 0xe2, 0x58, 0x99,
	0xf8, 0xa9, 0x44, 0x6d, 0xe2, 0xcc, 0x76, 0x36, 0xf6, 0x07, 0xf0, 0x7f, 0x23, 0x27, 0xf6, 0xa2,
	0x45, 0x15, 0xe2, 0xe6, 0xc4, 0xdf, 0xfb, 0xbe, 0xdf, 0xe7, 0x07, 0xc9, 0x4f, 0x55, 0x8a, 0x2d,
	0x9e, 0x37, 0x4a, 0x1a, 0x49, 0x27, 0xfd, 0x17, 0xfb, 0x08, 0x47, 0x97, 0x06, 0x2b, 0xba, 0x84,
	0x69, 0x69, 0xb0, 0xda, 0x94, 0x22, 0x0d, 0xb2, 0x30, 0x27, 0xf4, 0x19, 0xcc, 0x05, 0xea, 0x42,
	0x95, 0x8d, 0x29, 0x65, 0x9d, 0x86, 0x59, 0x98, 0xc7, 0x74, 0x01, 0x13, 0x5e, 0xc9, 0xb6, 0x36,
	0x29, 0xc9, 0xc2, 0x3c, 0x62, 0x5b, 0x98, 0x7e, 0xe3, 0xc5, 0x8e, 0x6f, 0x91, 0x9e, 0x40, 0x72,
	0xc7, 0x15, 0xfe, 0x92, 0xad, 0x46, 0xef, 0x12, 0x59, 0x97, 0xb6, 0xd1, 0x9b, 0x56, 0xa3, 0xb2,
	0x3f, 0xc3, 0x2c, 0xc8, 0x09, 0x8d, 0x21, 0xf8, 0xdd, 0x1b, 0xd8, 0xe3, 0x7d, 0x7a, 0xd4, 0x1d,
	0x5f, 0x41, 0x64, 0x09, 0x74, 0x1a, 0x65, 0x24, 0x9f, 0xaf, 0x92, 0x73, 0xc7, 0x6b, 0xf1, 0xd8,
	0x29, 0x24, 0x57, 0x78, 0xd3, 0xa2, 0x36, 0xdf, 0x55, 0x5b, 0xec, 0x0e, 0xa7, 0xb1, 0xaf, 0xb0,
	0x70, 0x38, 0xfa, 0x8b, 0xe4, 0x02, 0x05, 0x3d, 0x86, 0x99, 0xb1, 0x03, 0x03, 0xd1, 0x78, 0x32,
	0xf4, 0x9c, 0x4d, 0x3f, 0xb9, 0x29, 0x85, 0x4e, 0x49, 0x46, 0x72, 0xc2, 0xfe, 0x04, 0x10, 0xaf,
	0x3f, 0xc9, 0xaa, 0xe2, 0xb5, 0xd0, 0xf4, 0x0c, 0x16, 0x83, 0x64, 0xa3, 0xf0, 0x26, 0x0d, 0xb2,
	0x20, 0x9f, 0xaf, 0x96, 0x1e, 0xd4, 0xbf, 0xc4, 0x19, 0xc4, 0x7d, 0xa6, 0xd5, 0x84, 0x9d, 0xe6,
	0xc4, 0x6b, 0x1e, 0x95, 0x78, 0x07, 0x93, 0x7d, 0x87, 0x99, 0x92, 0x4e, 0xf5, 0x7c, 0xe4, 0xe4,
	0x4a, 0xb0, 0x0b, 0x78, 0x7a, 0x85, 0xba, 0x91, 0xb5, 0x46, 0x77, 0x73, 0x29, 0x28, 0x05, 0x18,
	0x70, 0xdc, 0xce, 0x9e, 0x40, 0x84, 0x4a, 0x49, 0xd5, 0xa5, 0xc6, 0xec, 0x03, 0x2c, 0xd7, 0xc5,
	0xae, 0x96, 0x77, 0x7b, 0x14, 0x5b, 0xac, 0xb0, 0x36, 0x76, 0xcd, 0xba, 0x2d, 0x0a, 0xd4, 0xba,
	0x1b, 0x99, 0x8d, 0x47, 0x38, 0xc0, 0xb5, 0xcf, 0xd2, 0xf4, 0xfd, 0x28, 0xc3, 0x42, 0xbe, 0x1c,
	0xaa, 0x8c, 0x91, 0x4e, 0x81, 0xf0, 0x62, 0xe7, 0x2a, 0xbf, 0xf0, 0xba, 0x11, 0x02, 0xbb, 0x80,
	0xa4, 0xab, 0xbf, 0x56, 0xaa, 0xbc, 0xe5, 0xfb, 0xff, 0x5d, 0x11, 0x7b, 0x0d, 0xb3, 0xcf, 0xb8,
	0x2f, 0x6f, 0x51, 0xdd, 0x1f, 0x2a, 0xcf, 0x7e, 0x40, 0x7c, 0xfd, 0xb0, 0xac, 0xb7, 0x30, 0xe5,
	0xbd, 0xbf, 0xc3, 0x7e, 0xd8, 0xc0, 0xa3, 0xec, 0x37, 0x10, 0x8b, 0xde, 0x13, 0x85, 0xe3, 0x3e,
	0xf6, 0x42, 0x1f, 0xc6, 0x56, 0x00, 0xeb, 0xe1, 0x4d, 0x5c, 0xc9, 0xe0, 0x9f, 0x25, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xbc, 0x0f, 0x3c, 0x92, 0x6d, 0x03, 0x00, 0x00,
}
