// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bridge.proto

/*
Package bridge is a generated protocol buffer package.

It is generated from these files:
	bridge.proto

It has these top-level messages:
	Item
	Package
	UCommands
	UResponses
	ACommands
	AResponses
	ResponsePackageId
	RequestTruck
	TruckArrival
	PackagesLoaded
*/
package bridge

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Item struct {
	ItemId           *int64  `protobuf:"varint,1,req,name=item_id" json:"item_id,omitempty"`
	Description      *string `protobuf:"bytes,2,req,name=description" json:"description,omitempty"`
	Amount           *int32  `protobuf:"varint,3,req,name=amount" json:"amount,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Item) Reset()                    { *m = Item{} }
func (m *Item) String() string            { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()               {}
func (*Item) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Item) GetItemId() int64 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *Item) GetDescription() string {
	if m != nil && m.Description != nil {
		return *m.Description
	}
	return ""
}

func (m *Item) GetAmount() int32 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

type Package struct {
	WarehouseId      *int64  `protobuf:"varint,1,req,name=warehouse_id" json:"warehouse_id,omitempty"`
	TruckId          *int32  `protobuf:"varint,2,req,name=truck_id" json:"truck_id,omitempty"`
	UpsUserId        *int64  `protobuf:"varint,3,opt,name=ups_user_id" json:"ups_user_id,omitempty"`
	X                *int32  `protobuf:"varint,4,req,name=x" json:"x,omitempty"`
	Y                *int32  `protobuf:"varint,5,req,name=y" json:"y,omitempty"`
	Items            []*Item `protobuf:"bytes,6,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Package) Reset()                    { *m = Package{} }
func (m *Package) String() string            { return proto.CompactTextString(m) }
func (*Package) ProtoMessage()               {}
func (*Package) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Package) GetWarehouseId() int64 {
	if m != nil && m.WarehouseId != nil {
		return *m.WarehouseId
	}
	return 0
}

func (m *Package) GetTruckId() int32 {
	if m != nil && m.TruckId != nil {
		return *m.TruckId
	}
	return 0
}

func (m *Package) GetUpsUserId() int64 {
	if m != nil && m.UpsUserId != nil {
		return *m.UpsUserId
	}
	return 0
}

func (m *Package) GetX() int32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *Package) GetY() int32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *Package) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type UCommands struct {
	PackageIdReq     []*Package      `protobuf:"bytes,1,rep,name=package_id_req" json:"package_id_req,omitempty"`
	TruckReq         *RequestTruck   `protobuf:"bytes,2,opt,name=truck_req" json:"truck_req,omitempty"`
	Loaded           *PackagesLoaded `protobuf:"bytes,3,opt,name=loaded" json:"loaded,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *UCommands) Reset()                    { *m = UCommands{} }
func (m *UCommands) String() string            { return proto.CompactTextString(m) }
func (*UCommands) ProtoMessage()               {}
func (*UCommands) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UCommands) GetPackageIdReq() []*Package {
	if m != nil {
		return m.PackageIdReq
	}
	return nil
}

func (m *UCommands) GetTruckReq() *RequestTruck {
	if m != nil {
		return m.TruckReq
	}
	return nil
}

func (m *UCommands) GetLoaded() *PackagesLoaded {
	if m != nil {
		return m.Loaded
	}
	return nil
}

type UResponses struct {
	Error            *string              `protobuf:"bytes,1,req,name=error" json:"error,omitempty"`
	PackageIds       []*ResponsePackageId `protobuf:"bytes,2,rep,name=package_ids" json:"package_ids,omitempty"`
	Trucks           *TruckArrival        `protobuf:"bytes,3,opt,name=trucks" json:"trucks,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *UResponses) Reset()                    { *m = UResponses{} }
func (m *UResponses) String() string            { return proto.CompactTextString(m) }
func (*UResponses) ProtoMessage()               {}
func (*UResponses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UResponses) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *UResponses) GetPackageIds() []*ResponsePackageId {
	if m != nil {
		return m.PackageIds
	}
	return nil
}

func (m *UResponses) GetTrucks() *TruckArrival {
	if m != nil {
		return m.Trucks
	}
	return nil
}

type ACommands struct {
	Arrival          *TruckArrival `protobuf:"bytes,1,opt,name=arrival" json:"arrival,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *ACommands) Reset()                    { *m = ACommands{} }
func (m *ACommands) String() string            { return proto.CompactTextString(m) }
func (*ACommands) ProtoMessage()               {}
func (*ACommands) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ACommands) GetArrival() *TruckArrival {
	if m != nil {
		return m.Arrival
	}
	return nil
}

type AResponses struct {
	Error            *string `protobuf:"bytes,1,req,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AResponses) Reset()                    { *m = AResponses{} }
func (m *AResponses) String() string            { return proto.CompactTextString(m) }
func (*AResponses) ProtoMessage()               {}
func (*AResponses) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AResponses) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type ResponsePackageId struct {
	PackageId        *int64  `protobuf:"varint,1,req,name=package_id" json:"package_id,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *ResponsePackageId) Reset()                    { *m = ResponsePackageId{} }
func (m *ResponsePackageId) String() string            { return proto.CompactTextString(m) }
func (*ResponsePackageId) ProtoMessage()               {}
func (*ResponsePackageId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ResponsePackageId) GetPackageId() int64 {
	if m != nil && m.PackageId != nil {
		return *m.PackageId
	}
	return 0
}

func (m *ResponsePackageId) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

type RequestTruck struct {
	WarehouseId      *int32 `protobuf:"varint,1,req,name=warehouse_id" json:"warehouse_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *RequestTruck) Reset()                    { *m = RequestTruck{} }
func (m *RequestTruck) String() string            { return proto.CompactTextString(m) }
func (*RequestTruck) ProtoMessage()               {}
func (*RequestTruck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RequestTruck) GetWarehouseId() int32 {
	if m != nil && m.WarehouseId != nil {
		return *m.WarehouseId
	}
	return 0
}

type TruckArrival struct {
	TruckId          *int32 `protobuf:"varint,1,req,name=truck_id" json:"truck_id,omitempty"`
	WarehouseId      *int32 `protobuf:"varint,2,req,name=warehouse_id" json:"warehouse_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TruckArrival) Reset()                    { *m = TruckArrival{} }
func (m *TruckArrival) String() string            { return proto.CompactTextString(m) }
func (*TruckArrival) ProtoMessage()               {}
func (*TruckArrival) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *TruckArrival) GetTruckId() int32 {
	if m != nil && m.TruckId != nil {
		return *m.TruckId
	}
	return 0
}

func (m *TruckArrival) GetWarehouseId() int32 {
	if m != nil && m.WarehouseId != nil {
		return *m.WarehouseId
	}
	return 0
}

type PackagesLoaded struct {
	PackageIds       []int64 `protobuf:"varint,1,rep,name=package_ids" json:"package_ids,omitempty"`
	TruckId          *int32  `protobuf:"varint,2,req,name=truck_id" json:"truck_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PackagesLoaded) Reset()                    { *m = PackagesLoaded{} }
func (m *PackagesLoaded) String() string            { return proto.CompactTextString(m) }
func (*PackagesLoaded) ProtoMessage()               {}
func (*PackagesLoaded) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *PackagesLoaded) GetPackageIds() []int64 {
	if m != nil {
		return m.PackageIds
	}
	return nil
}

func (m *PackagesLoaded) GetTruckId() int32 {
	if m != nil && m.TruckId != nil {
		return *m.TruckId
	}
	return 0
}

func init() {
	proto.RegisterType((*Item)(nil), "Item")
	proto.RegisterType((*Package)(nil), "Package")
	proto.RegisterType((*UCommands)(nil), "UCommands")
	proto.RegisterType((*UResponses)(nil), "UResponses")
	proto.RegisterType((*ACommands)(nil), "ACommands")
	proto.RegisterType((*AResponses)(nil), "AResponses")
	proto.RegisterType((*ResponsePackageId)(nil), "ResponsePackageId")
	proto.RegisterType((*RequestTruck)(nil), "RequestTruck")
	proto.RegisterType((*TruckArrival)(nil), "TruckArrival")
	proto.RegisterType((*PackagesLoaded)(nil), "PackagesLoaded")
}

func init() { proto.RegisterFile("bridge.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0xeb, 0xd3, 0x30,
	0x18, 0xc7, 0x49, 0xfb, 0x6b, 0xb7, 0x3c, 0xed, 0x36, 0x8d, 0x3b, 0x04, 0x44, 0x0d, 0x41, 0xb0,
	0x20, 0xf4, 0xb0, 0xc3, 0xbc, 0x78, 0x19, 0x9e, 0x06, 0x1e, 0x64, 0xb8, 0x73, 0x89, 0x6d, 0x98,
	0x65, 0x6b, 0xd3, 0x25, 0xad, 0x2f, 0xff, 0xbd, 0x24, 0xed, 0x5e, 0x8a, 0xfb, 0xdd, 0xc2, 0xf3,
	0xfa, 0xc9, 0xf7, 0xfb, 0x40, 0xfc, 0x43, 0x97, 0xc5, 0x41, 0xa6, 0x8d, 0x56, 0xad, 0xe2, 0x9f,
	0xe1, 0x69, 0xdb, 0xca, 0x8a, 0x2c, 0x60, 0x52, 0xb6, 0xb2, 0xca, 0xca, 0x82, 0x22, 0xe6, 0x25,
	0x3e, 0x79, 0x05, 0x51, 0x21, 0x4d, 0xae, 0xcb, 0xa6, 0x2d, 0x55, 0x4d, 0x3d, 0xe6, 0x25, 0x98,
	0xcc, 0x21, 0x14, 0x95, 0xea, 0xea, 0x96, 0xfa, 0xcc, 0x4b, 0x02, 0xae, 0x61, 0xf2, 0x4d, 0xe4,
	0x47, 0x71, 0x90, 0x64, 0x09, 0xf1, 0x6f, 0xa1, 0xe5, 0x4f, 0xd5, 0x19, 0x79, 0x9b, 0xf2, 0x02,
	0xa6, 0xad, 0xee, 0xf2, 0xa3, 0x8d, 0xd8, 0x11, 0x81, 0x9d, 0xdb, 0x35, 0x26, 0xeb, 0x8c, 0xd4,
	0x36, 0xe8, 0x33, 0x94, 0xf8, 0x04, 0x03, 0xfa, 0x43, 0x9f, 0x5c, 0x1e, 0x03, 0xfa, 0x4b, 0x03,
	0xf7, 0x5c, 0x42, 0x60, 0x99, 0x0c, 0x0d, 0x99, 0x9f, 0x44, 0xab, 0x20, 0xb5, 0xa4, 0xbc, 0x01,
	0xbc, 0xff, 0xa2, 0xaa, 0x4a, 0xd4, 0x85, 0x21, 0x0c, 0xe6, 0x4d, 0x0f, 0x90, 0x95, 0x45, 0xa6,
	0xe5, 0x99, 0x22, 0x57, 0x3b, 0x4d, 0x2f, 0x5c, 0x0c, 0x70, 0x4f, 0x60, 0x93, 0x1e, 0x43, 0x49,
	0xb4, 0x9a, 0xa5, 0x3b, 0x79, 0xee, 0xa4, 0x69, 0xbf, 0xdb, 0x04, 0x79, 0x07, 0xe1, 0x49, 0x89,
	0x42, 0xf6, 0x30, 0xd1, 0x6a, 0x71, 0xe9, 0x35, 0x5f, 0x5d, 0x98, 0xe7, 0x00, 0xfb, 0x9d, 0x34,
	0x8d, 0xaa, 0x8d, 0x34, 0x64, 0x06, 0x81, 0xd4, 0x5a, 0x69, 0xf7, 0x43, 0x4c, 0x3e, 0x40, 0x74,
	0x23, 0x30, 0xd4, 0x73, 0xeb, 0x49, 0x7a, 0xa9, 0x1f, 0x46, 0x6d, 0x0b, 0xf2, 0x06, 0x42, 0x07,
	0x62, 0x86, 0x35, 0xb3, 0xd4, 0xad, 0xdf, 0x68, 0x5d, 0xfe, 0x12, 0x27, 0xfe, 0x11, 0xf0, 0xe6,
	0xfa, 0xad, 0xb7, 0x30, 0x11, 0x7d, 0x9c, 0xa2, 0x47, 0xc5, 0xaf, 0x01, 0x36, 0xcf, 0x11, 0xf1,
	0x35, 0xbc, 0xfc, 0x7f, 0x3b, 0x01, 0xb8, 0x61, 0x0e, 0xe6, 0x5c, 0xfb, 0xac, 0x2c, 0x98, 0xbf,
	0x87, 0x78, 0xa4, 0xcb, 0x23, 0x47, 0x03, 0xbe, 0x86, 0xf8, 0x1e, 0x65, 0xe4, 0x30, 0x1a, 0x6c,
	0x1b, 0xf7, 0x39, 0xdf, 0xf9, 0x27, 0x98, 0x8f, 0x65, 0xb5, 0x97, 0x70, 0xaf, 0x9c, 0x35, 0xee,
	0xc1, 0xc1, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x0b, 0xa9, 0x19, 0x44, 0xb0, 0x02, 0x00, 0x00,
}
